# Generated by Django 5.0.7 on 2024-08-18 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_Name', models.CharField(max_length=150)),
                ('Number_of_tickets', models.IntegerField(default=500)),
                ('Event_description', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200)),
                ('Event_Date', models.DateField(default=django.utils.timezone.now)),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event', to='User_App.customuser')),
                ('Events_members', models.ManyToManyField(blank=True, to='User_App.customuser')),
            ],
        ),
    ]
